#!/bin/sh /etc/rc.common

START=98
STOP=15

USE_PROCD=1
PROG=/usr/bin/wifi_connect_blink.sh

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    # Cleanup
    rm -f /tmp/wifi_client_connecting
    rm -f /var/run/wifi_connect_blink.pid
}
